import { useQuery } from '@apollo/client'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { graphql } from '../gql'

const MetaQuery = graphql(/* GraphQL */ `
  query Meta {
    meta: NETWORK___meta {
      block {
        hash
        timestamp
        number
      }
    }
  }
`)

export default function Home() {
  const { data, error } = useQuery(MetaQuery)

  return (
    <>
      <Head>
        <title>Graph Client | Apollo Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Graph Client, w/ apollo issues demo</h1>
        <div>{data?.meta?.block?.number ?? 'No data returned'}</div>
        {error != null ? <div>{error.message}</div> : null}
      </main>
    </>
  )
}
